### PR TITLE
Problem: devtools needed during AM17 upgrades are broken

### PR DESCRIPTION
**Pull request by scollazo**
setup_reading_from_client_conf() was deprecated

### CODE REVIEW

**Comment by scollazo** [comment]
@sevein we don't usually care about backward compatibility, any reason why this case is different?

I'm thinking on looking for the ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_SERVER instead of the hardcoded "localhost". That should be enough to make it work in older versions.

**Comment by sevein** [comment]
As far as I know we do care a lot about backward compatibility and any breaking change is generally considered a bug. This is because we're not consuming formal contracts which is a point I've made in the past. I wrote about this once in #43.

**Comment by jhsimpson** [comment]
this change was necessary for me to upgrade archivematica from 1.5 to 1.7 - in order to run rebuild-elasticsearch-aip-index-from-files after the upgrade.

I think it should be easy to make this backwards compatible as well.

**Comment by sevein** [comment]
@jhsimpson before we do more work here can you try to enumerate for us the tools in this repo that are needed between upgrades of Archivematica releases? I want them to become formal management commands.

Instead of fixing `tools/rebuild-elasticsearch-aip-index-from-files` here and creating a new devtools package (https://github.com/artefactual-labs/am-packbuild/issues/137, please read the discussion there too), I want to add it to our [management module](https://github.com/artefactual/archivematica/tree/951f5efe7564ef538d9fa81a165fc461491cd9b2/src/dashboard/src/main/management/commands).

I see that https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/maintenance/maintenance/ mentions some of the tools in this repo. If they're necessary during the upgrade I think we should make sure that they're also mentioned during the upgrade notes. I can file a bug in archivematica-docs to cover that problem and any necessary change if we agree on transferring these scripts to AM as formal management commands.

**Comment by sevein** [comment]
Replaced by https://github.com/artefactual/archivematica/issues/1026.

**Pull request closed without merging**
